using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using Platformer.Utilities;

namespace Platformer.Services
{
    public class CoroutineService : GenericMonoSingleton<CoroutineService>
    {
        // TODO: string will not be used for referencing and mapping a Coroutine.
        // TODO: we will use a unique id for coroutines. This unique id will generated by either CoroutineService or another Utility class
        // TODO: The owner of the Coroutine (let's say PlayerService) will hold the reference to this unique id and can use it to stop that coroutine whenever required.
        // TODO: Required changes will need to be made in this whole Service accordingly.
        
        private Dictionary<int, Coroutine> runningCoroutines = new();


        protected override void Awake()
        {
            base.Awake();
            DontDestroyOnLoad(gameObject);
        }


        public static int StartCoroutine(IEnumerator routine)
        {
            if (Instance == null)
            {
                GameObject coroutineServiceObject = new GameObject();
                coroutineServiceObject.AddComponent<CoroutineService>();
            }
            return Instance.StartCoroutineInternal(routine);
        }

        public static void StopCoroutine(int id)
        {
            if (Instance != null)
            {
                Instance.StopCoroutineInternal(id);
            }
        }

        public static new void StopAllCoroutines()
        {
            if (Instance != null)
            {
                Instance.StopAllCoroutinesInternal();
            }
        }

        private int StartCoroutineInternal(IEnumerator routine)
        {
            // TODO: The ID for the coroutine should be generated and cached outside of CoroutineService.cs
            // TODO: For example, PlayerMovementController should generate and cache the ID of PlayerSlideCoroutine
            int id = UniqueIdGenerator.GenerateUniqueId();
            Coroutine coroutine = base.StartCoroutine(routine);

            if (runningCoroutines.ContainsKey(id))
                base.StopCoroutine(runningCoroutines[id]);

            runningCoroutines[id] = coroutine;
            return id;
        }

        private void StopCoroutineInternal(int id)
        {
            if (runningCoroutines.TryGetValue(id, out Coroutine coroutine))
            {
                base.StopCoroutine(coroutine);
                runningCoroutines.Remove(id);
            }
        }

        private void StopAllCoroutinesInternal()
        {
            base.StopAllCoroutines();
            runningCoroutines.Clear();
        }
    }
}