using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using Platformer.Utilities;

namespace Platformer.Services
{
    // TODO: string will not be used for referencing and mapping a Coroutine.
    // TODO: we will use a unique id for coroutines. This unique id will generated by either CoroutineService or another Utility class
    // TODO: The owner of the Coroutine (let's say PlayerService) will hold the reference to this unique id and can use it to stop that coroutine whenever required.
    // TODO: Required changes will need to be made in this whole Service accordingly.
    public class CoroutineService : GenericMonoSingleton<CoroutineService>
    {
        private Dictionary<string, Coroutine> runningCoroutines = new Dictionary<string, Coroutine>();

        protected override void Awake()
        {
            base.Awake();
            DontDestroyOnLoad(gameObject);
        }

        public static Coroutine StartCoroutine(IEnumerator routine, string id = null)
        {
            if (Instance == null)
            {
                GameObject go = new GameObject("CoroutineService");
                go.AddComponent<CoroutineService>();
            }
            return Instance.StartCoroutineInternal(routine, id);
        }

        public static new void StopCoroutine(string id)
        {
            if (Instance != null)
            {
                Instance.StopCoroutineInternal(id);
            }
        }

        public static new void StopAllCoroutines()
        {
            if (Instance != null)
            {
                Instance.StopAllCoroutinesInternal();
            }
        }

        private Coroutine StartCoroutineInternal(IEnumerator routine, string id)
        {
            Coroutine coroutine = base.StartCoroutine(routine);
            if (!string.IsNullOrEmpty(id))
            {
                if (runningCoroutines.ContainsKey(id))
                {
                    base.StopCoroutine(runningCoroutines[id]);
                }
                runningCoroutines[id] = coroutine;
            }
            return coroutine;
        }

        private void StopCoroutineInternal(string id)
        {
            if (runningCoroutines.TryGetValue(id, out Coroutine coroutine))
            {
                base.StopCoroutine(coroutine);
                runningCoroutines.Remove(id);
            }
        }

        private void StopAllCoroutinesInternal()
        {
            base.StopAllCoroutines();
            runningCoroutines.Clear();
        }
    }
}